# Generated by Django 4.2.20 on 2025-04-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price_starting',
            field=models.FloatField(blank=True, help_text='Optional field', null=True, verbose_name='Price Starting With ($)'),
        ),
        migrations.AddField(
            model_name='book',
            name='publish_month',
            field=models.IntegerField(blank=True, help_text='Optional field', null=True, verbose_name='Publish Date (Month)'),
        ),
        migrations.AddField(
            model_name='book',
            name='publish_year',
            field=models.IntegerField(blank=True, help_text='Optional field', null=True, verbose_name='Publish Date (Year)'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, help_text='Optional field', max_length=255, null=True, verbose_name='Publisher'),
        ),
    ]
