# Generated by Django 4.2.20 on 2025-04-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_price_starting_book_publish_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='сategory',
            field=models.CharField(help_text='Required field', null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.CharField(help_text='Required field', max_length=500, verbose_name='Tags'),
        ),
    ]
