# Generated by Django 4.2.20 on 2025-04-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_book_сategory_alter_book_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='сategory',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Category'),
        ),
    ]
