# Generated by Django 4.2.20 on 2025-04-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_book_сategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='сategory',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
